name: CI con gradle

on:
  push:
      branches: [ master ] #se ejecutará cuando hagamos un push a esta rama
  workflow_dispatch: #y también podremos ejecutar el workflos manualmente desde github
    
jobs:
  build:
      runs-on: ubuntu-latest #trabajaremos sobre una máqina ubuntu
      permissions:
        contents: read #el repo solo se puede leer
        packages: write #para tener acceso a los binarios resultantes de los build
        
      steps:
          ### CONFIGUGRACIÓN DEL ENTORNO: jdk 8 y dradle 2.1 ###
        - uses: actions/checkout@v2 #descarga el repositorio en el ejecutor
        - name: Set up JDK 8
          uses: actions/setup-java@v2
          with:
            java-version: '8'
            distribution: 'adopt'
            server-id: github #value of the distribuionManagmente/repository/id field of the pom.xml
            settings-path: ${{ github.workspace }} #n for the settings.xml file
        - name: set up gradle
          uses: gradle/gradle-build-action@v2
          with:
            gradle-version: 2.1
            
        ### BUILDS ###
        - name: hacer build del frontend
          working-directory: src/Clients
          run: ./gradlew build
          
        - name: hacer build del backend
          working-directory: src/Backend/OrderService
          run: ./gradlew build test
            
          
        
